name = "Arsênico"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ba8d8b55a510ae4d73a07150c488d1bd9f61e2979c02ff56649d781dff2d0e0"

[versions]
forge = "36.2.40"
minecraft = "1.16.5"
