name = "Arsênico"
author = "AmeMeida"
version = "2.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e127160a05ef7f93508d1b624a40f8bf5c7e83dfcaf2e6b46b5575e1d47b17b"

[versions]
forge = "36.2.40"
minecraft = "1.16.5"
