name = "Arsênico"
author = "AmeMeida"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6585393feabb3fc911e191933984751e752841a0111f1899a95c2e275bfeea27"

[versions]
forge = "36.2.40"
minecraft = "1.16.5"
